name: Deploy DotNet Web App to Server
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: iis-dev-server

    steps:

      - name: Checkout of the Code
        uses: actions/checkout@v3

      - name: Install .NET Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'

      - name: Verify the .NET Installation
        run: dotnet --version

      - name: Build the Application with .NET
        run: dotnet build --configuration Release

      - name: Publish the Deployment Package in public folder
        run: dotnet publish -c Release -o public

      - name: Create a Artifact using from the public folder
        uses: actions/upload-artifact@v3
        with:
          name: public-folder-to-be-deployed-to-iis
          path: public

      - name: zip the folder
        run:  Compress-Archive .\public -DestinationPath .\public.zip

      - name: check directory
        run: dir

      - name: Create a Artifact using from the public folder
        uses: actions/upload-artifact@v3
        with:
          name: public zip file
          path: public.zip
        

  deploy:
    runs-on: iis-dev-server
    needs: build
    steps:

      - name: copy files from from working folder to iis directory
        run: |
          iisreset /stop
          Copy-Item ./public/* C:/inetpub/wwwroot/ -Recurse -Force
          iisreset /start


  artifactoryUpload:
    needs: build

  #  runs-on: ubuntu-latest
    runs-on: iis-dev-server
    steps:
    
      - name: Checkout of the Code
        uses: actions/checkout@v3

      - name: Get Artifact using from the public folder
        uses: actions/download-artifact@v3
        with:
          name: public zip file
          path: public.zip

      - name: push to artifactory
       # run: curl -uiisrunner:AP4SqrHG18g1eGsrU2im4oUi2Mh -T "public.zip" "https://dotnetrepo.jfrog.io/artifactory/dotnetapp/public.zip"
        run: curl --user iisrunner:AP4SqrHG18g1eGsrU2im4oUi2Mh --uploadfile "public.zip" "https://dotnetrepo.jfrog.io/artifactory/dotnetapp/public.zip"