name: Deploy DotNet Web App to Server
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows latest

    steps:

      - name: Checkout of the Code
        uses: actions/checkout@v3

      - name: Install .NET Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'

      - name: Verify the .NET Installation
        run: dotnet --version

      - name: Build the Application with .NET
        run: dotnet build --configuration Release

      - name: Publish the Deployment Package in public folder
        run: dotnet publish -c Release -o public

      - name: Create a Artifact using from the public folder
        uses: actions/upload-artifact@v3
        with:
          name: public-folder-to-be-deployed-to-iis
          path: public

  # deploy:
  #   runs-on: iis-dev-server
  #   needs: build
  #   steps:

  #     - name: copy files from from working folder to iis directory
  #       run: |
  #         iisreset /stop
  #         Copy-Item ./public/* C:/inetpub/wwwroot/ -Recurse -Force
  #         iisreset /start


  artifactoryUpload:
    needs: build

    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout of the Code
        uses: actions/checkout@v3

      - name: Get Artifact using from the public folder
        uses: actions/download-artifact@v3
        with:
          name: public-folder-to-be-deployed-to-iis
          path: public

      - name: publish to artifactory
        uses: advancedcsg-open/action-jfrog-cli@master
        with:
          url: 'https://dotnetrepo.jfrog.io/artifacts/'
          #credentials type: 'apikey'
          #apikey: ${{ secrets.RT_APIKEY }}
          credentials type: 'username'
          user: ${{ secrets.RT_USER }}
          password: ${{ secrets.RT_PASSWORD }}
          args: u "public/*" "default-generic-local/" --recursive=true --build-name=MyFirstDotNetApp